name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/portfolio-backend
            git pull origin main
            npm install
            npx prisma generate
            npx prisma db push
            npm run build
            pm2 restart portfolio-backend

      - name: Notify Discord
        if: always()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: ${{ job.status == 'success' && 'info' || 'error' }}
          details: "Deployment of portfolio-backend ${{ job.status }}!"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}